@startuml
actor Client
entity Server
entity Authenticator

group Request Message
    Client -> Server: **LOGIN** Request
    Client -> Server: Username and Password
end

Server -> Authenticator: Check Username and Password

alt Login Success
    Authenticator --> Server: User is Valid
    group Response Message
        Server --> Client: **SUCCESS** Response
        Server --> Client: SUCCESS Header Message
        Server --> Client: Session Key
    end

else Login Denied
    Authenticator --> Server: Is not registered user

    group Response Message
        Server --> Client: **DENIED** Response
        Server --> Client: DENIED Reason Header Message
    end

else Login Error
    Authenticator --> Server: Is not registered user
    group Response Message
        Server --> Client: **ERROR** Response
        Server --> Client: ERROR Reason Header Message
    end
end
@enduml