@startuml
actor Client
entity Server
entity Authenticator

Client -> Server: **LOGIN** Request
Client -> Server: Username and Password

Server -> Authenticator: Check Username and Password

group Login Success
    Authenticator --> Server: User is Valid
    Server --> Client: **SUCCESS** Response
    Server --> Client: SUCCESS Header Message
    Server --> Client: Session Key
end

group Login Denied
    Authenticator --> Server: Is not registered user
    Server --> Client: **DENIED** Response
    Server --> Client: DENIED Reason Header Message
end

group Login Error
    Authenticator --> Server: Is not registered user
    Server --> Client: **ERROR** Response
    Server --> Client: ERROR Reason Header Message
end
@enduml