@startuml
actor Client
entity Server
Database "Session Store"

group Request Message
    Client -> Server: **LOGOUT** Request
    Client -> Server: Session Key
end

Server -> "Session Store": Delete Session Key if it exists

alt Logout Success
    "Session Store" --> Server: Session Key Deleted
    group Response Message
        Server --> Client: **SUCCESS** Response
        Server --> Client: SUCCESS Header Message
    end
else Logout Error
    "Session Store" --> Server: Session Key not valid
    group Response Message
        Server --> Client: **ERROR** Response
        Server --> Client: ERROR Reason Header Message
    end
end
@enduml